### ISSUE TITLE
Tests with iOS7 DP3?

### ISSUE THREAD

**Issue by GantMan** [colinta/teacup#103]
Every teacup project I run in iOS7 DP3 fails with the following.

```
** Terminating app due to uncaught exception 'NoMethodError', reason: 'teacup_view.rb:125:in `restyle!:': undefined method `each' for nil:NilClass (NoMethodError)
    from teacup_view.rb:125:in `restyle!:'
    from teacup_controller.rb:106:in `teacupDidLoad'
    from ui_view_controller.rb:6:in `viewDidLoad'
    from app_delegate.rb:6:in `application:didFinishLaunchingWithOptions:'
```

**Comment by colinta** [comment]
Locally, that line corresponds to:

```
125:    subviews.each { |subview| subview.restyle!(orientation) }
```

If `subviews` returns `nil`, that's very strange indeed...

**Comment by GantMan** [comment]
as a heads up this is with MotionTemplate and other Teacup driven projects.

**Comment by pschlund** [comment]
I ran into the same issue. It looks like the non-public class UINavigationTransitionView returns nil for subviews. I have not yet had time to investigate the root cause, but as quick hack to get up and running again, I added nil checks in two places in teacup_view.rb.

**Comment by colinta** [comment]
Odd, huh?

K, what I'll do here is replace `subviews` with `teacup_subviews` and define that method on UIView to return `subviews || []`

Or, if someone beats me to it, I'll merge your pull request! :-D
