### ISSUE TITLE
Orientation styles doesn't work

### ISSUE THREAD

**Issue by holgersindbaek** [colinta/teacup#116]
I can't get orientation styles to work when the iphone re-orientates. They work well enough when initializing the view, but not when the view re-orientates. 

```
style :label,
    landscape: {
      hidden: true
    },
    portrait: {
      hidden: false
    }
```

I'm handling orientation manually btw.   

Any ideas of why this might happen?

**Comment by colinta** [comment]
The specs have tests for orientation changes, so it's definitely strange that such a simple use case would fail.

Are you running iOS 7?  I cannot support iOS 7 in teacup until the NDA is removed.

**Comment by holgersindbaek** [comment]
No… Normal iOS 6.  

Do you think it has something to do with me handling the orientation manually?  

## 

All the best

Holger Sindbaek
Holgersindbaek.com (http://Holgersindbaek.com)

Co-founder
Uninkd.com (http://Uninkd.com)
Meer.li (http://Meer.li)

**Comment by colinta** [comment]
Possibly; I've never heard of such a thing, actually.  What do you mean by that?

**Comment by colinta** [comment]
Are you implementing `willAnimateRotationToInterfaceOrientation(duration:)`?

This is the teacup method:

``` ruby
def willAnimateRotationToInterfaceOrientation(orientation, duration:duration)
  view.restyle!(orientation)
end
```

You can call super, or call `restyle!` like it is here.
