### ISSUE TITLE
`autorotateMask': undefined local variable or method `orientation'

### ISSUE THREAD

**Issue by aler** [colinta/teacup#118]
this code from my controller

  def supportedInterfaceOrientations
    self.autorotateMask
  end

iOS 6, teacup 2.1.9

full message
ui_view_controller.rb:59:in `autorotateMask': undefined local variable or method`orientation' for #SignupController:0xb2ef300 (NameError)
    from signup_controller.rb:19:in `supportedInterfaceOrientations'
    from app_delegate.rb:12:in`application:didFinishLaunchingWithOptions:'

**Comment by colinta** [comment]
yikes, thanks for the heads up; fixed in 2.1.10
