### ISSUE TITLE
sizeToFit not applied correctly on labels with multilines

### ISSUE THREAD

**Issue by Flink** [colinta/teacup#120]
Hi!
I’m using teacup with promotion, sugarcube and sweettea.
I’m creating a label with a lot of text and I want it to autoresize its height. Currently I’m doing this by setting numberOfLines to 0 and calling sizeToFit on it and it works well.
So I’ve converted my current code to teacup stylesheet but when I set `sizeToFit: true` it creates a label with a very large width but on a single line.

**Comment by colinta** [comment]
Pasting the style code would help, but just make sure the order is correct; sizeToFit should be called after size and numberOfLines and such...

**Comment by Flink** [comment]
Right, sorry!

Here is my current working code:
controller/screen: https://gist.github.com/Flink/6620948
and the associated stylesheet: https://gist.github.com/6620958

If I comment out `overview_label.sizeToFit` and set `sizeToFit: true` in the stylesheet then the problem occurs :/

Maybe I’m doing something wrong?

**Comment by otzy007** [comment]
I'm having the same issue. The text it's not break into lines neither from setting lineBreakMode, numberOfLines = 0 and sizeToFit from both the controller or the stylesheet.

@Flink did you find a solution for it?

**Comment by otzy007** [comment]
Setting a constraint like this:

```
 constrain(:right).equals(:superview, :right)
```

in my case fixed the problem

**Comment by colinta** [comment]
There were some things wrong with the "priority" feature which have resolved this bug.
