### ISSUE TITLE
Reload stylesheet cache and then restyle!

### ISSUE THREAD

**Issue by holgersindbaek** [colinta/teacup#122]
How can I do this?

My issue is that I have some variables in my stylesheet, that I'm changing. After I've changed those variables, I would like to call restyle! on my view, so the variables gets applied.

Problem is that Teacup caches the stylesheet and therefore uses the old variables.

This is my code:

```
include BaseHelper

Teacup::Stylesheet.new :root do

  # BASE
  style :root,
    backgroundColor: light_background_color.uicolor #variable

end
```

I've read that "Stylesheets should not be modified once they are created - they cache styles by name (per orientation).", but is there a way around this?

**Comment by colinta** [comment]
sure, you can clear the cache

```
stylesheet.stylesheet_cache.clear
```

**Comment by holgersindbaek** [comment]
Hmmm. Doesn't seem to do anything.

If I just do - stylesheet.stylesheet_cache.clear - and then - @content_view.restyle! - the new "styles" don't get applied.

If I do this:

```
stylesheet.stylesheet_cache.clear
Teacup::Stylesheet.new :root
@content_view.restyle!
```

Nothing happens either, but I get an error:

```
TEACUP WARNING: A stylesheet with the name :root has already been created.
```

I'm not sure if the cace gets cleared. What do you think?

**Comment by colinta** [comment]
There's no point in calling `Teacup::Stylesheet.new` again, but check the `clear` method by using `get_stylesheet_cache`

```
stylesheet.get_stylesheet_cache(:root, nil (or a view), nil (or an orientation constant))
```

**Comment by holgersindbaek** [comment]
Have tried these 3, both before and after I do - stylesheet.stylesheet_cache.clear:

   puts stylesheet.get_stylesheet_cache(:root, @content_view, :portrait)
   puts stylesheet.get_stylesheet_cache(:root, @content_view, nil)
   puts stylesheet.get_stylesheet_cache(:root, nil, nil)

I always get nil. What do you make out of that?

**Comment by colinta** [comment]
You should get nil, that means the cache has been cleared.

Oh, you know what just occurred to me, the body of the stylesheet will not be rerun... and that's probably the whole point, you're changing values that are in the block.  Hmm, the block is actually released after it's run, so what you're trying to do is just outside the design of how teacup works.

**Comment by holgersindbaek** [comment]
Hmmm... And there's no way I can change the dynamic values in the stylesheet? 

Or maybe a way I can apply a stylesheet specific to an element?

**Comment by colinta** [comment]
sure, each view can have its own stylesheet, but then subviews will inherit that stylesheet as well

**Comment by holgersindbaek** [comment]
Ok. And can you re-apply those style sheets dynamically, so the updated variables goes through?  

## 

Holger Sindbaek
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by colinta** [comment]
you can try... it sounds like you're trying to do things "outside the box"

instead of relying on stylesheets, i would just send new styles via a hash to `UIView#style()` method.

**Comment by holgersindbaek** [comment]
Sounds interesting. Can you specify a bit more? I can't remember seeing that in the documentation.   

## 

Holger Sindbaek
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by holgersindbaek** [comment]
@colinta I'd still love if you could elaborate a bit more. Hope you have the time.

**Comment by colinta** [comment]
This should help a little; you can pass a style hash to the `UIView#style()` method. [Teacup as a Utility](https://github.com/rubymotion/teacup#teacup-as-a-utility)

**Comment by holgersindbaek** [comment]
I'm gonna close this one. Thanks for the help.
