### ISSUE TITLE
Excessive console logging in 2.1.12

### ISSUE THREAD

**Issue by cacrawford** [colinta/teacup#126]
I'm seeing a seemingly endless stream of console output like that below when I'm running on the IOS7 simulator in RubyMine.

...
{:stylename=>TCS::StateNotifications, :target=>nil, :orientation=>nil}
{:stylename=>UIViewController, :target=>nil, :orientation=>nil}
{:stylename=>UIViewController, :target=>nil, :orientation=>nil}
{:stylename=>BubbleWrap::UIViewControllerWrapper, :target=>nil, :orientation=>nil}
{:stylename=>BubbleWrap::UIViewControllerWrapper, :target=>nil, :orientation=>nil}
{:stylename=>Teacup::Controller, :target=>nil, :orientation=>nil}
{:stylename=>Teacup::Controller, :target=>nil, :orientation=>nil}
{:stylename=>Teacup::Layout, :target=>nil, :orientation=>nil}
{:stylename=>Teacup::Layout, :target=>nil, :orientation=>nil}
{:stylename=>UIResponder, :target=>nil, :orientation=>nil}
{:stylename=>UIResponder, :target=>nil, :orientation=>nil}
{:stylename=>NSObject, :target=>nil, :orientation=>nil}
{:stylename=>NSObject, :target=>nil, :orientation=>nil}
{:stylename=>Kernel, :target=>nil, :orientation=>nil}
{:stylename=>Kernel, :target=>nil, :orientation=>nil}
{:stylename=>:list_cell_size, :target=>#SkuResultsController:0x14b65e60, :orientation=>nil}
...

**Comment by colinta** [comment]
Well this is odd, I _did_ have some logging code like that, but searching through the git log, I see that I never committed it.  So how the heck do YOU have that code... if you can find the code that is outputting this, I'll remove it, but for the life of me I don't see any trace of it in the code!

You can open the gem using `bundle show teacup`, and search for `:orientation`. Or to find all logging messages: `\b(p|puts|NSLog|print)\b`

**Comment by zackola** [comment]
p stylename: stylename, target: target, orientation: orientation on line 218 of stylesheet.rb

Seems to not be in the latest github version but somehow got into rubygems?

**Comment by colinta** [comment]
Ohhh, that makes sense, if I pushed to rubygems before committing. Dang. I'll have to push another minor release.

**Comment by cacrawford** [comment]
Thanks. I did search for NSLog in the gem source without success and obviously couldn't find the problem in the changelog. I guess that answers the question.

**Comment by colinta** [comment]
No excessive logging in 2.1.13 (which brings back caching, too!).
