### ISSUE TITLE
Is restyle! with animation already built into Teacup?

### ISSUE THREAD

**Issue by holgersindbaek** [colinta/teacup#131]
I'd like to do exactly this:

```
UIView.animate { @container.restyle! }
```

It works fine, but was wondering if it was already built into Teacup?

**Comment by colinta** [comment]
There are a few animate methods: `animate_to_stylename`, `animate_to_styles`, `animate_to_style`.  Not sure what you're doing _before_ calling `restyle!`, but maybe one of these can help.

**Comment by holgersindbaek** [comment]
I've looked at them and I'm not sure I can use them (they don't seem to work for me at least).

I'm basically just rotating the phone, so I want all the styles re-applied for the new dimensions.  

## 

All the best

Holger Sindbaek
Holgersindbaek.com (http://Holgersindbaek.com)

Co-founder
Uninkd.com (http://Uninkd.com)
Meer.li (http://Meer.li)

**Comment by holgersindbaek** [comment]
Anyway… 'UIView.animate { @container.restyle! }' works fine as well.

Thanks for the quick answer.
