### ISSUE TITLE
Custom UIView in gem won't be styled with Teacup

### ISSUE THREAD

**Issue by holgersindbaek** [colinta/teacup#132]
I'm trying to make a custom UIView that I want to style with Teacup. The styling doesn't seem to get applied though.

I'm doing this as a gem. Here's the view (lib/project/status_bar.rb):

```
class StatusBar < UIView

  def initWithFrame(frame)

    super.tap do
      self.stylesheet = :status_bar
      layout(self, :status_bar_view) do
        @notice_view = subview(UIView, :notice_view)
        @activity_view = subview(UIView, :activity_view)
        @success_view = subview(UIView, :success_view)
        @error_view = subview(UIView, :error_view)
      end
    end

  end

end
```

And the style sheet (lib/project/status_bar_style.rb):

```
Teacup::Stylesheet.new :status_bar do

  style :status_bar_view,
    width: 300,
    height: 400,
    left: 0,
    top: 0,
    backgroundColor: "#000000".uicolor

end
```

I get no errors, but no styling either. Any suggestions on what I'm doing wrong?

**Comment by holgersindbaek** [comment]
@colinta I've looked a bit more into it and it's only when the custom_view.rb file is inside lib/project, that things are not working. If I move the file up into the app folder, then things work perfectly.

What's going on here? Is it just impossible to use Teacup in a gem?

**Comment by colinta** [comment]
My guess is that the stylesheet file isn't getting included.  put a 'puts' in that file to be sure.

**Comment by holgersindbaek** [comment]
I've tried it where I put the style sheet code into the custom uiview as well. So that shouldn't be the problem.   

## 

All the best

Holger Sindbaek
Holgersindbaek.com

**Comment by holgersindbaek** [comment]
You can take a look at the issue here - https://github.com/holgersindbaek/status_bar.

I'm calling the custom view inside app/controllers/demo_controller.rb.

@colinta Any guess? Is there examples of other gems using Teacup?

**Comment by holgersindbaek** [comment]
I figured it out. I had to add this in my status_bar.rb file:

  teacup_insert_point = nil
  app.files.each_index do |index|
    file = app.files[index]
    if file =~ /teacup/
      teacup_insert_point = index + 1
    elsif teacup_insert_point
      # found one, so stop looking
      break
    end
  end

  Dir.glob(File.join(File.dirname(**FILE**), 'project/*_/_.rb')).reverse.each do |file|
    app.files.insert(teacup_insert_point, file)
  end

I got it from sweettea. @colinta Can you explain me what exactly it does and why it's needed?

**Comment by colinta** [comment]
It inserts the gem's files before all the files in the `app/` folder.

**Comment by colinta** [comment]
Or, in this case, all the files before `teacup/`

**Comment by holgersindbaek** [comment]
Hmmm… don't fully get that. Should that happen by adding Teacup as a gem dependency?

## 

All the best

Holger Sindbaek
Holgersindbaek.com (http://Holgersindbaek.com)

Co-founder
Uninkd.com (http://Uninkd.com)
Meer.li (http://Meer.li)

**Comment by colinta** [comment]
No, gem dependencies have nothing to do with the RubyMotion compilation process; the order of the files in `app.files` is important if the `detect_dependencies` feature can't determine the proper order (which, in this case, it could not)

**Comment by holgersindbaek** [comment]
Ok… Now I think I get it.  

Thanks for the explanation. Rock on.  

## 

All the best

Holger Sindbaek
Holgersindbaek.com (http://Holgersindbaek.com)

Co-founder
Uninkd.com (http://Uninkd.com)
Meer.li (http://Meer.li)
