### ISSUE TITLE
Multiple :extends doesn't seem to be working

### ISSUE THREAD

**Issue by holgersindbaek** [colinta/teacup#137]
Or am I wrong?

I have these 2 basic "styles":

```
style :full_screen,
  top: 0,
  left: 0,
  portrait: {
    width: "100%",
    height: "100%"
  },
  landscape: {
    width: "100%",
    height: "100%"
  },
  backgroundColor: :white

style :shadow,
  shadow: {
    opacity: 0.05,
    radius: 7,
    offset: [7, 0],
    color: :black
  },
  layer: {
    shouldRasterize: true,
    rasterizationScale: UIScreen.mainScreen.scale
  }
```

And I'd like to apply both of these styles to some views, like this:

```
style :table, extends: :full_screen, extends: :shadow,
  portrait: {
    width: 320
  },
  landscape: {
    width: 320
  },
  allowsSelection: true,
  userInteractionEnabled: true,
  bounces: false,
  separatorColor: K_clear
```

It doesn't seem to be working though. Seems like only the last :extends gets applied.

Am I right in this? Is it out of the scope of Teacup to be able to apply multiple extends styles to a style?

**Comment by holgersindbaek** [comment]
I took a look at the code and it seems like this is working:

```
style :table, extends: [:full_screen, :shadow]
```

Is that true? If it is, then it would probably be a nice thing to have in the README.

**Comment by colinta** [comment]
good call, I'll add a note about that.

**Comment by holgersindbaek** [comment]
Awesome... keep up the good work.
