### ISSUE TITLE
Using a NSWindow subclass with subclass of TeacupWindowController

### ISSUE THREAD

**Issue by briangonzalez** [colinta/teacup#138]
Hi there!

How might one go about using a custom `NSWindow` subclass in conjunction with an `TeacupWindowController`? It seems as if the `TeacupWindowController` creates a window.

If I call `myController.setWindow(myWindow)`, my defined layout ceases to work.

Thanks in advance.

**Comment by colinta** [comment]
Easy! Override the `loadWindow` method.

https://github.com/rubymotion/teacup/blob/master/lib/teacup-osx/core_extensions/ns_window_controller.rb
