### ISSUE TITLE
Rotation is slow

### ISSUE THREAD

**Issue by holgersindbaek** [colinta/teacup#139]
I'm making heavy use of teacup and have many views where I style the width and height depending in the orientation. Example:

```
style :full_screen,
  top: 0,
  left: 0,
  portrait: {
    width: "100%",
    height: "100%"
  },
  landscape: {
    width: "100%",
    height: "100%"
  },
  backgroundColor: :white
```

Problem is that rotation has become really slow. It takes 2+ full seconds before the app rotates. When it rotates though, the rotation animation is really nice and smooth.

What makes my views take so long before they rotate? Is there some heavy calculations going on in the background, since it takes more than 2 seconds before anything happens?

**Comment by holgersindbaek** [comment]
No suggestions? Is this normal or might I be doing something wrong?

**Comment by holgersindbaek** [comment]
@colinta Can you give me any answer to where I should begin and end, if I want to improve the speed? Which part of Teacup could be slowing this down? Which files would you start looking into?

**Comment by colinta** [comment]
The part that is slowing things down could one of these things:
- the caching has been disabled, because it was causing huge memory leaks
- if you have lots of `extends:` and `import:` statements, that would take longer to generate the style properties

as always, including code would help.

**Comment by holgersindbaek** [comment]
@colinta I thought caching was back on - https://github.com/rubymotion/teacup/commit/058d78bf91406b3690a8c76f7390489caf273828 - but that's not the case?

I do have a good deal of extends and imports (:full_screen is an extension I use on 5-10 views). If I write everything out then and stop using extends, do you think that would speed things up? Seems weird to me, that using extend a lot should cause over a 2 seconds delay.

Here is some more code, of what I think might be causing the delay:

base.rb

```
style :full_screen,
  top: 0,
  left: 0,
  portrait: {
    width: "100%",
    height: "100%"
  },
  landscape: {
    width: "100%",
    height: "100%"
  },
  backgroundColor: :white

style :shadow,
  shadow: {
    opacity: 0.05,
    radius: 7,
    offset: [7, 0],
    color: :black
  },
  layer: {
    shouldRasterize: true,
    rasterizationScale: UIScreen.mainScreen.scale
  }
```

table.rb

```
style :table, extends: [:full_screen, :shadow],
  portrait: {
    width: 320
  },
  landscape: {
    width: 320
  },
  allowsSelection: true,
  userInteractionEnabled: true,
  bounces: false,
  separatorColor: K_clear
```

I have a good deal of views that are getting extended.

**Comment by colinta** [comment]
Oh that's right, I did add it back.  Hmm... I'd open up the teacup source code and add some `NSLog("%@ at %@",  NSDate.new.to_i, __LINE__)`, starting in the rotation code.  See if you can find the culprit.

Does it take a long time _every_ time, or just the first time?

**Comment by holgersindbaek** [comment]
@colinta It's each and every time, not just the first time.

I've tried to narrow down if there's a specific view that takes most of the time and I've narrowed it down to the root view. 

I have a root view (with rounded corners), that I have all the other views in, so it looks like they all have rounded corners, when they slide in and out. I've attached an image, if that was too convoluted:

![ios simulator screen shot nov 14 2013 4 05 46 pm](https://f.cloud.github.com/assets/698979/1541863/6c7e89b6-4d3e-11e3-8be4-2cbf3efa5756.png)

The code for that looks like this:

root_controller.rb

```
# Layout code via teacup
layout :root do
  @root_container = subview(UIView, :root_container) do
    @alert_container = subview(UIView, :alert_container) do
      @alert_label = subview(MSLabel, :alert_label)
      @yes_button = subview(QBFlatButton, :yes_button)
      @yes_button.when(UIControlEventTouchUpInside) do 
        NSUserDefaults[:rated] = true
        IRate.sharedInstance.openRatingsPageInAppStore
        0.3.second.later { hide_alert }
      end
      @no_button = subview(QBFlatButton, :no_button)
      @no_button.when(UIControlEventTouchUpInside) { hide_alert }
    end

    @splash_screen = subview(UIImageView, :splash_screen)
  end

  # Instantiate controllers
  $root_vc = self
  $detail_vc = DetailController.new
  $table_vc = TableController.new
  $intro_vc = IntroController.new if publication_name_blank?

  # Add subviews (WHERE I ADD MY CHILD VIEWS)
  @root_container.addSubview($detail_vc.view)
  @root_container.addSubview($table_vc.tableView)
  @root_container.addSubview($intro_vc.view) if publication_name_blank?

  # Bring splash screen to front
  @root_container.bringSubviewToFront(@splash_screen)
end 
```

If I remove the below teacup code, that controls the root view, then things are nice and speedy:

root.rb

```
style :root_container, extends: :full_screen,
  backgroundColor: K_grey_light_xx,
  clipsToBounds: true,
  layer: {  
    masksToBounds: true,
    cornerRadius: 5
  },
  landscape: {
    height: "100%-20",
    top: 20,
  },
  portrait: {
    height: "100%-20",
    top: 20,
  }
```

Can you think of a particular reason that the root view takes so long time to rotate? Is it because this particular view has so many other views inside?

**Comment by holgersindbaek** [comment]
@colinta It's become much better somehow.

I don't know exactly what happened. Nice, but annoying I don't know what caused it.
