### ISSUE TITLE
uninitialized constant NSRect (NameError)

### ISSUE THREAD

**Issue by JonasNielsen** [colinta/teacup#143]
It appears that issue #105 is back after upgrading to RubyMotion 2.15 (OS X app build on Mavericks)

```
(main)> 2013-11-20 18:37:09.608 Screenmailer[7881:303] handler.rb:76:in `block in apply:': uninitialized constant CGRect (NameError)
    from handler.rb:70:in `apply:'
    from handler.rb:51:in `block in apply_hash:'
    from handler.rb:46:in `apply_hash:'
    from ns_view.rb:25:in `apply_style_properties:'
    from teacup_view.rb:305:in `style:'
    from ns_view.rb:29:in `style:'
    from teacup_view.rb:129:in `restyle!:'
    from teacup_view.rb:131:in `block in restyle!:'
    from teacup_view.rb:131:in `restyle!:'
    from teacup_controller.rb:108:in `teacupDidLoad'
    from ns_view_controller.rb:14:in `loadView'
    from waiting_view_controller.rb:12:in `loadView'
```

Previously I managed to fix the issue by adding this to the RubyMotion project:

``` ruby
Teacup.handler NSView, :frame do |target, frame|
  # odd... if I changed these to .is_a?, weird errors happen.  Use ===
  if Symbol === frame && frame == :full
    if target.superview
      frame = target.superview.bounds
    else
      frame = target.frame
    end
  elsif Array === frame && frame.length == 4
    frame = [
        [Teacup::calculate(target, :width, frame[0]), Teacup::calculate(target, :height, frame[1])],
        [Teacup::calculate(target, :width, frame[2]), Teacup::calculate(target, :height, frame[3])]
      ]
  elsif (Array === frame && frame.length == 2) || NSRect === frame # HACK IS HERE
    frame = [
        [Teacup::calculate(target, :width, frame[0][0]), Teacup::calculate(target, :height, frame[0][1])],
        [Teacup::calculate(target, :width, frame[1][0]), Teacup::calculate(target, :height, frame[1][1])]
      ]
  end
  target.frame = frame
end
```

But the same problem happens with this modification, with NSRect being the uninitialized constant:

```
(main)> 2013-11-20 18:33:07.687 Screenmailer[7436:303] handler.rb:76:in `block in apply:': uninitialized constant NSRect (NameError)
    from handler.rb:70:in `apply:'
    from handler.rb:51:in `block in apply_hash:'
    from handler.rb:46:in `apply_hash:'
    from ns_view.rb:25:in `apply_style_properties:'
    from teacup_view.rb:305:in `style:'
    from ns_view.rb:29:in `style:'
    from teacup_view.rb:129:in `restyle!:'
    from teacup_view.rb:131:in `block in restyle!:'
    from teacup_view.rb:131:in `restyle!:'
    from teacup_controller.rb:108:in `teacupDidLoad'
    from ns_view_controller.rb:14:in `loadView'
    from waiting_view_controller.rb:12:in `loadView'
```

Is there any way of killing this for good? Or another workaround to use?

**Comment by JonasNielsen** [comment]
Just downgraded to RubyMotion 2.14 and things seem to be working with this version.

**Comment by colinta** [comment]
k, file a report with HipByte (`motion support`)

**Comment by JonasNielsen** [comment]
Done, thanks.

**Comment by alloy** [comment]
From the 10.9 documentation on `NSRect`:

> When building for 64 bit systems, or building 32 bit like 64 bit, NSRect is typedef’d to CGRect.

I’m going to discuss with Laurent if we can automate such typedefs, but that will probably not happen anytime soon, alternatively we could maybe make those aliases ourselves.

In the meantime, you should be able to work around it by defining the alias like so:

``` ruby
NSRect = CGRect unless defined?(NSRect)
```

**Comment by JonasNielsen** [comment]
Thanks alloy. Should the alias be defined somewhere special?

It appears that CGRect is also not defined (RM 2.15):
`*** Terminating app due to uncaught exception 'NameError', reason: 'uninitialized constant CGRect (NameError)`

**Comment by alloy** [comment]
Anywhere in the top-level namespace. E.g.

``` ruby
NSRect = CGRect unless defined?(NSRect)

class AppDelegate
end
```

`CGRect` definitely works for me. Can you try to `rake clean` first? And or otherwise report your environment? (E.g. OS X version.)

**Comment by JonasNielsen** [comment]
Unfortunately, it's a no go for me. Just confirmed after `rake clean`:

```
NSRect = CGRect unless defined?(NSRect)
class AppDelegate
..
end
```

```
*** Terminating app due to uncaught exception 'NameError', reason: 'uninitialized constant CGRect (NameError)
```

osx template
`motion -v` 2.15 
`$:.unshift("/Library/RubyMotion/lib")`
OS X 10.9 (13A603)
Macbook Pro, late 2008

**Comment by alloy** [comment]
@JonasNielsen Can you reproduce this with a completely new blank application? Also, what Xcode version do you have and are you targeting an older OS X version as the deployment target?

**Comment by JonasNielsen** [comment]
Let me give it a try with a blank app. I'm targeting 10.9 with Xcode 5.0.2
installed

On Fri, Nov 22, 2013 at 11:07 AM, Eloy Durán notifications@github.comwrote:

> @JonasNielsen https://github.com/JonasNielsen Can you reproduce this
> with a completely new blank application? Also, what Xcode version do you
> have and are you targeting an older OS X version as the deployment target?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rubymotion/teacup/issues/143#issuecomment-29061846
> .

## 

Mvh
Jonas

**Comment by JonasNielsen** [comment]
The bug appears to be triggered by including the Webkit framework. It's reproduced in this project:
https://github.com/JonasNielsen/motion-cgrect-bug/

**Comment by Tensho** [comment]
The same problem has happend. Looks like OSX RubyMotion drags behind again.

**Comment by alloy** [comment]
@JonasNielsen Thanks a lot for the sample, I can reproduce it. This is caused by another 64-bit bug, which is documented, including a workaround, [here](http://hipbyte.myjetbrains.com/youtrack/issue/RM-312).

For the typedef issue I have created the following ticket: http://hipbyte.myjetbrains.com/youtrack/issue/RM-332

**Comment by JonasNielsen** [comment]
Ok thanks @alloy. What would you say we can expect in terms of getting it fixed?

I was able to remove Webkit from the project for now, but I may require it again soon.

**Comment by alloy** [comment]
@JonasNielsen Alas, as a policy, we don’t give out release ETAs. It is our intention to fix this in the next release, though!

**Comment by colinta** [comment]
Is there anything that needs fixing in Teacup?  Doesn't look like it...
