### ISSUE TITLE
Translucent and titleTextAttributes

### ISSUE THREAD

**Issue by stefanvermaas** [colinta/teacup#145]
Hi,

I've got a question about the options: "translucent" and "titleTextAttributes". When setting translucent to false ( to disable the transparency ), I'm getting this error:

``` shell
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** Illegal property type, c for appearance setter, _installAppearanceSwizzlesForSetter:'
```

Thereby I need to set the title color, but it doesn't seem to be possible with Teacup yet, though the function is there. Is there some workaround or am I doing something wrong?

This is my code:

``` ruby
# Global appearance styling
Teacup::Appearance.new do

  style UINavigationBar,
    barTintColor: '#2c3e50'.uicolor,
    tintColor: '#ffffff'.uicolor,
    titleTextAttributes: [
      color: '#ffffff'.uicolor
    ]

  style UIBarButtonItem, when_contained_in: UINavigationBar,
    tintColor: '#ffffff'.uicolor

end
```

Cheers!

**Comment by colinta** [comment]
You might need to add a "dummy" method for those methods (see the README, search for "dummy"), and the value you're passing to `titleTextAttributes` doesn't look very sensical here (an array of Hashes, instead of a Hash).

``` ruby
[array_of:  'hashes']  # => [{:array_of=>"hashes"}]
# vs
{ hash: true }
```

Plus, I don't think `color` is one of the attributes in [NSString - Text Attribute Keys](https://developer.apple.com/library/ios/documentation/uikit/reference/NSString_UIKit_Additions/Reference/Reference.html#//apple_ref/doc/uid/TP40006893).  Try `UITextAttributeTextColor`.

**Comment by stefanvermaas** [comment]
Hi @colinta 

Thanks! I'm not quite sure how this works, can you give me any heads up? What I'm trying to do is this: [Custom navigationview](http://johnriselvato.com/ios-7-custom-navigationview-or-navigationviewcontroller/). Here you also see how the titleTextAttributes color is set.

Thereby I see that translucent is already defined in the dummy.rb, but it still isn't working. Can you explain what that dummy.rb exactly does and how I can use it? The read me isn't very clear about this.

Cheers.

**Comment by colinta** [comment]
I've added some more information to the README: https://github.com/rubymotion/teacup#the-dummy

Does that clear it up?

**Comment by stefanvermaas** [comment]
It does. Though I not sure why translucent isn't working, but I'll figure that out! Thanks!

**Comment by bgribbin** [comment]
Hi Stefan,

Wondering if you managed to change your Navbar title text color to white in the end?

I've been trying with my app and not had any luck. My code so far is:

Teacup::Appearance.new do

  style UINavigationBar,
    barTintColor: "#44aa85".uicolor,
    titleTextAttributes: { UITextAttributeTextColor: "#ffffff".uicolor}

end

Many thank for any help

Ben

**Comment by stefanvermaas** [comment]
Hi @bgribbin 

I've not fixed it yet. I'll try to make the changes in my own fork soon. 
I'll keep you up-to-date.

Cheers.

**Comment by stefanvermaas** [comment]
I've found the problem. We need to use the old ruby object style for setting the font. It's an compiler error of RubyMotion, which compiles the object to hash symbols. Reference: [stackoverflow](http://stackoverflow.com/questions/13162329/uinavigationbar-appearance-in-rubymotion-not-working).

``` ruby
Teacup::Appearance.new do
  style UINavigationBar,
      barTintColor: '#ffffff'.uicolor,
      tintColor: '#ffffff'.uicolor,
      titleTextAttributes: {
        UITextAttributeTextColor => '#ffffff'.uicolor
      }
end
```

**Comment by colinta** [comment]
Just a heads up, the compiler is _correct_ in working this way, it's part of the Ruby language specification, not a compiler error.

``` ruby
{ symbol: 'value' }
{ :symbol => 'value' }
key = :symbol
{ key => 'value' }  # this is what you're doing above, using a constant value as the 'key'
```

In other words, if you output the value of `UITextAttributeTextColor`, you will _not_ get the string `"UITextAttributeTextColor"`, you get `"NSColor"`

**Comment by colinta** [comment]
Which means you _could_ do this in your stylesheet (but don't, you should use the constant)

``` ruby
Teacup::Appearance.new do
  style UINavigationBar,
      titleTextAttributes: {
        NSColor: '#ffffff'.uicolor
      }
```
