### ISSUE TITLE
setLabel("Test", forSegment:0)

### ISSUE THREAD

**Issue by holgersindbaek** [colinta/teacup#148]
Is something like that possible to do inside the layout file?

I have an NSSegmentedControl and need to set the different segments:

```
@calc = subview(NSView, :calc) do
    @size_control = subview(NSSegmentedControl, :size_control)
end

def windowDidLoad
    teacupDidLoad
    @ size_control("No", forSegment:0)
end
```

It's just feels clumsy to set it in windowDidLoad.

**Comment by colinta** [comment]
Sure!  You could write a handler for that, see the relevant section in the readme.

**Comment by holgersindbaek** [comment]
Great, thanks.
