### ISSUE TITLE
styles don´t restyle inside button event block

### ISSUE THREAD

**Issue by michelson** [colinta/teacup#149]
Hi Teacup`ers

I´m trying to change styles for a UIButton when is pressed, I don´t know why is not working, maybe Im doing something wrong for sure.

```
 def will_appear
    @btn.when(UIControlEventTouchUpInside){

      @btn.stylename = :loading_submit
      #@btn.restyle!
      data_hash = { user:
                    { email: @email.text,
                      password: @pass.text
                    }
                  }

      Utils.login( data_hash ) do
        open_root_screen WelcomeController.new(nav_bar: true) if Utils.have_token?
      end

      @btn.stylename = :submit
      #@btn.restyle!
    }
  end
```

if I do the btn.style = :foo , from motion console it restyle correctly, also I´ve tried @btn.restyle! within the UIControlEventTouchUpInside block but with no luck

thanks in advance

best

**Comment by colinta** [comment]
You're setting the stylename twice, so I would only expect the `:submit` styles to be applied at the end of the block, is that the goal?  (in other words, setting `stylename = :loading` has no effect)

**Comment by michelson** [comment]
Hi @colinta , 
the goal is style button with  :loading style temporarily for the duration of login http request, then back to :submit style.
should I remove style and then apply style ?

best

**Comment by colinta** [comment]
Ah, you probably want something like this:

``` ruby
@btn.stylename = :loading_submit
Utils.login( data_hash ) do
  open_root_screen WelcomeController.new(nav_bar: true) if Utils.have_token?
  @btn.stylename = :submit
end
```

**Comment by colinta** [comment]
Though, just on a style note, the use of the global `Utils.have_token?` here could be replaced with the more functional:

``` ruby
@btn.stylename = :loading_submit
Utils.login( data_hash ) do |has_token|
  if has_token
    open_root_screen WelcomeController.new(nav_bar: true)
    @btn.stylename = :submit
  # else
  #   @btn.stylename = :another_style_maybe
  end
end
```

**Comment by michelson** [comment]
yeah , it works!!

thanks @colinta
