### ISSUE TITLE
Style undefined

### ISSUE THREAD

**Issue by mleung** [colinta/teacup#20]
I'm getting an exception when trying to call the style method like in the docs, thusly:

  def viewDidLoad
    view.addSubview(Teacup.style(:field, UITextField.new))
    true
  end

undefined method `style' for Teacup:Class (NoMethodError)

Has anyone seen this?

**Comment by colinta** [comment]
The README is in desperate need of an update - my apologies!

I am working on implementing things the way ConradIrwin has laid them out, and then I'll be updating the README, and hopefully the wiki, too.

**Comment by mleung** [comment]
Thanks for the response! Looking forward to the new docs.

**Comment by colinta** [comment]
@mleung the README has been updated!  Also, the project in samples/Hai should work for you, too.

To see some of the changes we're expecting soon, checkout my [teacup-example](https://github.com/colinta/teacup-example) project.  It uses my branch of teacup, with some new features and syntax.  Expect it to get merged soon.
