### ISSUE TITLE
Sample not working

### ISSUE THREAD

**Issue by aberbenni** [colinta/teacup#23]
(main)> 2012-06-04 17:43:12.166 Hai[20510:f803] **\* Terminating app due to uncaught exception 'NoMethodError', reason: 'stylesheet.rb:93:in `initialize:': undefined method`include' for Teacup::Stylesheet::IPadVertical:Teacup::Stylesheet (NoMethodError)

**Comment by colinta** [comment]
You'll need to be using my branch, called `no_const` (https://github.com/colinta/teacup/tree/no_const)

**Comment by aberbenni** [comment]
Well, now I have:

(main)> 2012-06-04 17:50:34.690 Hai[20925:f803] **\* Terminating app due to uncaught exception 'NameError', reason: 'uninitialized constant Teacup::StyleSheet (NameError)

**Comment by colinta** [comment]
k, i'm gonna fresh install it and see if i can reproduce... probably a submodule thing...

**Comment by colinta** [comment]
oh, wait, what example are you running?  teacup-example?

i totally misunderstood... i thought this was a bug on the teacup-example project... ignore what i said about using no_const.  my bad!  btw, stop by irc #teacup, we'll get it figured out :-)

**Comment by aberbenni** [comment]
The Hai sample: https://github.com/rubymotion/teacup/tree/master/samples/Hai

**Comment by colinta** [comment]
gotcha - yeah that code was all out of date.  i've updated it now, i'm gonna test it, but give it a try.

**Comment by colinta** [comment]
@aberbenni thanks for this heads up.  I've fixed the sample app, and it's working on my machine

```
cd samples/Hai
rake
```

I've added some new features to it, namely the `style UILabel` that @Markvilla pushed this morning, which is a similar feature to what you can do with `UIAppearance`, but with a more "css-like" feel.

Lemme know if you have any questions!

**Comment by aberbenni** [comment]
Now it works! Thanks.
