### ISSUE TITLE
Final proposal code does not work

### ISSUE THREAD

**Issue by aberbenni** [colinta/teacup#24]
I'm trying the code from final proposal but I receive errors during build.

./app/styles/stylesheets.rb:12: syntax error, unexpected tIDENTIFIER, expecting '}'
        frame: [[2, 2], [40, 40]],
             ^
./app/styles/stylesheets.rb:12: syntax error, unexpected ',', expecting keyword_end
./app/styles/stylesheets.rb:30: syntax error, unexpected tIDENTIFIER, expecting '}'
        textAlignment: :left.uialignment,
                     ^
./app/styles/stylesheets.rb:31: syntax error, unexpected tLABEL, expecting '='
        frame: [[44, 20], [138, 12]],
              ^
./app/styles/stylesheets.rb:31: syntax error, unexpected ',', expecting keyword_end
./app/styles/stylesheets.rb:35: syntax error, unexpected tIDENTIFIER, expecting '}'
        textAlignment: :right,
                     ^
./app/styles/stylesheets.rb:36: syntax error, unexpected ',', expecting keyword_end
./app/styles/stylesheets.rb:60: syntax error, unexpected ':', expecting '}'
        frame: [[0, 74], [768, 960]],
              ^
./app/styles/stylesheets.rb:60: syntax error, unexpected ',', expecting '}'

rake aborted!

Command failed with status (): [/usr/bin/env VM_KERNEL_PATH="/Library/Ruby...]

**Comment by ConradIrwin** [comment]
Hi @aberbenni can you paste/link the whole code? I'll try to fix the examples.

**Comment by aberbenni** [comment]
The code was copied by https://github.com/rubymotion/teacup/wiki/Final-Proposal:

**app/styles/stylesheets.rb**
**app/views/layouts.rb**
**app/controllers/main.rb**

 plus:

``` ruby
class AppDelegate
  def application(application, didFinishLaunchingWithOptions:launchOptions)
      @window = UIWindow.alloc.initWithFrame(UIScreen.mainScreen.bounds)     
      @window.rootViewController = MainViewController.alloc.init.tap{ |c| c.wantsFullScreenLayout = true }
      @window.makeKeyAndVisible
      true
  end
end
```

**Comment by colinta** [comment]
this code is way old, gotta close this, but @aberbenni if you're still having trouble, lemme know!

we're releasing teacup soon, check it out!
