### ISSUE TITLE
Before i send a pull request...

### ISSUE THREAD

**Issue by colinta** [colinta/teacup#25]
...wanted to have some "documented" chatting on github about my `no_const` branch.  It brings in tons of changes.
## minor changes
1. Adds a `stylesheet` method to TeacupViewController.  You can set a "default" stylesheet name or instance.
   
   ``` ruby
   class MyViewController < TeacupViewController
    stylesheet :my_view
    layout do
      # ...
    end
   end
   ```
2. Makes style name optional, which then defaults to `:__root__`, and sets the default stylename on the root view to `:__root__` as well, so you can style the top-level-view by declaring `style do ... end`.
   
   ``` ruby
   Teacup::Stylesheet.new :my_view
    # this becomes the style on the root view
    style({
      backgroundColor: UIColor.blueColor,
    })
   end
   ```
3. Stylename is also optional in the `Teacup::Layout#layout` method.
4. Added an `instance_eval`-style declaration syntax, which we got rid of long ago, but it's growing on me again.
   
   ``` ruby
   # new style:
   style :label do
    textColor  UIColor.blueColor
    left   10
    top    10
    width  100
    height 20
    landscape do
      left   10
      top    30
      width  150
      height 20
    end
   end
   
   # old style:
   style :label, {
    textColor  UIColor.blueColor
    left:   10,
    top:    10,
    width:  100,
    height: 20,
    landscape: {
      left:   10,
      top:    30,
      width:  150,
      height: 20,
    }
   }
   ```
   
   This uses a `Style` class that inherits from Hash and accepts a block. `method_missing` assigns values to `self[method_name]`
## major changes
1. Instead of `Teacup::Stylesheet::Ipad`, the stylesheets are available using `Teacup::Stylesheet[:stylesheet_name]`.
2. The stylesheet setter accepts a `:name`, and later looks it up.  This removes the dependency that `Stylesheet`s be loaded before controllers.  This code is in the `Teacup::View#stylesheet` getter.
3. Adds per-orientation-based styling!  This is a great feature, but a lot of things had to change to support it.
   
   Namely, adding `shouldAutorotate...` to `UIViewController` as a module doesn't work, the method doesn't get called.  So I changed it to `TeacupViewController`.  Given that this adds the class/instance methods `layout` and such I think this is a good thing, actually.
4. `UIView` includes `Teacup::View`, and `TeacupViewController` includes `Teacup::Layout`.  This is most controversial change; let's discuss!

**Comment by colinta** [comment]
from IRC:

```
colinta:
in looking at it now, the only curveball, i think, is the subview/layout stuff bing removed from UIVIew
the TeacupViewController isn't so bad, and I *tried* my damndest to monkey patch Cocoa to "see" the shouldAutorotate stuff...
but to no avail

cirwin:
well — if you can persuade me I don't want to use that I'm happy for it

colinta:
hehe
hmm... actually...
if I remove the stylesheet getter/setters from layout.rb,
and move them into teacup_view_controller
that would leave ONLY layout and subview methods in Teacup::Layout
then the only "hack" is bringing back the top_level_view method (which became unneeded)

cirwin:
sounds promising

colinta:
another way to do it: in teacup_view_controller, call `layout` on the view instead of on self
and then don't include Teacup::Layout in the controller at all

cirwin:
heh, that's quite a neat idea actually

colinta:
(just brainstorming here)
yeah, i think i like that, too...
```

**Comment by colinta** [comment]
new plan is to move controller code into lib/teacup/controller.rb, keep view code in lib/teacup/view.rb, and shared code (`layout`, `subview`) in lib/teacup/layout.rb.  working on it! :-)

**Comment by ConradIrwin** [comment]
I've put some fixes on https://github.com/ConradIrwin/teacup/commits/no_const that fix some of the breakages introduced by this change for my Commune app (not for pulling, just for reference). Please run the specs from time to time :p.

The main change I didn't unbreak was that properties are no-longer forwarded onto layouts. I assume you broke that deliberately; we should work out how to fix that better (maybe a :layout sub-hash, a la :portrait and :landscape, but with a better name).

Changes I like: 

minor 1
major 1,2,3 (and the proposal to move layout into UIView only from IRC).

Changes I don't mind:

minor 2,3. It seems a bit too magic, but maybe it's useful to optimize for the common case.

Changes I dislike:
minor 4:

It makes it very confusing as you can do styling in the block passed to style(), but not the block passed to layout()/subview(). [my argument asserts that being able to do styling in layout()/subview() is a good thing, and I think it is, so there].

**Comment by colinta** [comment]
the first use of `style ...` with no name was to have a place to put `landscape: true`, which is the minimum "style" needed to enable landscape orientation.  As a CSS-like-thing, though, it looks like default styles, rather than styles being applied to the root view.  I'll defer to your opinion (I'm not a fan of tricks that seem like magic)...

Couple changes this morning: brought back UIViewController extensions, and removed TeacupViewController.  In cases where you want to extend UITableViewController, this class hierarchy doesn't make sense.  Also a bug fix in `style`, and i had forgotten to add `Teacup::Layout` to the UIView class.

**Comment by colinta** [comment]
Hmm... so, what code goes in `Teacup::View`, and what code goes in `class UIView` extensions?

The thing is, I can move ALL the code from view.rb into ui_view.rb, and from controller.rb into ui_view_controller.rb.  But I can't do the opposite - things like `class << self` do not "work" in rubymotion when they are in a module.

I propose that we consolidate the code from the `Teacup::View` and `Teacup::Controller` modules into `UIView[Controller]` extensions.

**Comment by colinta** [comment]
The `:__root__` magic is gone.  style name is not being checked in the `Stylesheet#style` method, maybe it should be enforced to be there.  A `style` with no name doesn't _do_ anything now, but the method signature allows for it.

**Comment by colinta** [comment]
the `style` method no longer accepts a block, and it has super rotation powers. :-)

**Comment by colinta** [comment]
Hopefully I'll get testing worked out tonight or tomorrow, using teacup-example code and making sure the styling is applied.

It uses `layout`, `subview`, `style UILabel` and `style :style_name`, which is a pretty thorough test, I think.  The other thing to check would be changing the stylesheet during runtime, and making sure the views are updated.

**Comment by colinta** [comment]
closing? hmm... i wonder what's coming next...
