### ISSUE TITLE
teacup 0.3.11 breaks UIGlossyButton on upon styling

### ISSUE THREAD

**Issue by kibiz0r** [colinta/teacup#47]
Upgrading from 0.3.10 to 0.3.11 caused some odd behavior for me.

Using:

```
app.pods do
  pod 'UIGlossyButton'
end
```

This code:

```
@log_in_button = subview UIGlossyButton.alloc.initWithFrame([[50, 8], [220, 37]]),
  title: 'Log In'
```

Would produce a touchable button.

Since 0.3.11, the button doesn't respond to touches.
- UIButton still works fine
- UIGlossyButton works fine if I don't use teacup to set any properties

I poked around the code a bit and it seemed to be coming from `Teacup::Layout.layout:81`, which looked pretty odd to me...

```
if properties
  view.style(properties) if properties
end
```

I traced that to Teacup.apply (or apply_hash) at `UIView#style:120-124`, which also looked pretty odd to me...

```
def style(properties, orientation=nil)
  Teacup.apply_hash self, properties
  properties.each do |key, value|
    Teacup.apply self, key, value
  end
  ...
end
```

But I stopped there, so I'm not sure exactly what's causing it.

**Comment by colinta** [comment]
That is odd.  I would expect that the button would just not get styled, not that it would become unresponsive.

you've isolated this to a teacup version thing?

**Comment by kibiz0r** [comment]
It seems that way. Using 0.3.10 works, 0.3.11 doesn't. The actual cause might be an interaction of something else, I would have to try it outside of my project to be certain, but it only happens when teacup styles the button -- so if I don't set the title in that subview call, it continues on its merry way. (Title is not special here, it happens with any property.)

**Comment by colinta** [comment]
Any property?  O_O  I'm going through the code (starting at `subview`) and nothing there jumps out at me as auspicious.  This is a doozy of a pickle.  What view are you adding it to?  Just a vanilla `UIView`?

When I have time I'll setup a project that uses `UIGlossyButton`.

**Comment by colinta** [comment]
Are you using the github version?  I hadn't pushed recently (I had pushed, but to my fork, I forgot to push the fixes to _this_ repo).  I've pushed 0.3.12, which has all tests passing.

**Comment by colinta** [comment]
Has anyone tried this recently?  Or is there some code I can test against?

**Comment by colinta** [comment]
I was able to add a UIGlossyButton to a teacup project and style it, it was still responsive.
