### ISSUE TITLE
Misleading documentation bug in wiki page

### ISSUE THREAD

**Issue by skue** [colinta/teacup#48]
In the Layouts section of the Teacup wiki page, there's an example layout (app/views/layouts.rb) that subclasses UIView. The preceding text also says:

> You can extend from any UIView subclass, but the most common are containers like UIView and UITableCellView [sic]. The layout will be added to your view at the end of initialization, so as soon as you create your view, you can access any subviews that you make available using attr_accessor.

I spent a few hours struggling to get this to work before discovering there's no built-in support for layouts in UIView or UITableViewCell. Layouts work great for subclasses of UIViewController, but the layout methods are completely absent from z_core_extensions/ui_view.rb.

So is the the documentation incorrect, or is the code incomplete? My own preference is that it would be nice to define layouts as a UIView and UITableViewCell (especially the latter) without adding that code to the controller.

**Comment by colinta** [comment]
The documentation is wrong, I'm afraid. We've done pretty well documenting the code and keeping the README up to date, but the wiki pages were made long ago, and even though that page was edited just a couple months ago, I'm not even sure what that section is referring to. 

The correct place to put the `layout do...end` is in the UIViewController, which is done later. I don't know what the original intent of that section was, but I'll remove it or heavily modify it soon. 

I'm sorry you wasted the day on this, but I'm appreciative that you pointed it out.

**Comment by defvol** [comment]
I agree, would be great to be able to import stylesheets and layouts inside UIView classes

**Comment by colinta** [comment]
I've looked at what it would take to get that going, and I'm standing by the decision to leave stylesheets and layouts (the class `layout` method, that is) in the domain of the `UIViewController`s.  Here's why.

View controllers have an obvious place where subviews should be added (e.g. where the `layout` block should be applied), and that is in the `viewDidLoad` method.  The view has been requested and created, and just before it is handed over, the view hierarchy is created and styles are applied.  This is very sensible, I think, and only involves overriding the `viewDidLoad` method, which apple still claims "does nothing" by default.  Sweet.

There is not an analogous method on `UIView`.  A `UIView` is certainly free to create subviews and add them to itself, but the where and how is not clearly defined.  There is not a method (that **I** know of!) that we can override or implement that would be a sensible place to instantiate the `layout`.  In my own `UIView` classes, I add subviews in the initializer or sometimes in a `layoutSubviews` method, in which case I remove some or all of the existing subviews.

That said, there _is_ a stop-gap solution that is already available, and that is to use the `layout` and `subview` methods that are added by the `Teacup::Layout` module.  I have had good success with this - you can even add style names to your view, and write application-specific stylesheets for them.

I'm going to edit the wiki now, modifying the section about subclassing and moving most of the existing text into the Controller section.  I'm still open to arguments, but for now at least I think we should have the wiki reflect the current state of teacup.

**Comment by colinta** [comment]
Updated: https://github.com/rubymotion/teacup/wiki/Teacup

**Comment by defvol** [comment]
The best thing about having stylesheets in UIView classes, would be that the controller doesn't have to know about all the subviews that a particular view holds, for instance a subclass of a UITableViewCell.

@colinta For UIView subclasses, what about placing all the subviews in `initWithFrame`? I believe that could be a one time call to setup the layout and style for its subviews, don't you think? That could work for UIView subclasses where you may call super.initWithFrame:CGRectZero and configure `self` according to the stylesheet.

**Comment by defvol** [comment]
Or better yet, create a new initializer which then calls the designated initializers (e.g. initWithStylesheet will call initWithFrame:CGRectZero and start configuring self)

**Comment by colinta** [comment]
The missing feature that `UIViewController` can do, that `UIView` cannot, is to assign a stylesheet and subview hierarchy in the class body.  What you're proposing can already be done right now:

``` ruby
class MyView < UIView
  def initWithFrame(frame)
    super.tap
      subview(UIImageView, :my_image)
      subview(UILabel, :my_label)

      self.stylesheet = :a_stylesheet
    end
  end
end
```

I, personally, think this provides enough power to accomplish what you're asking for.  The reason I'm not excited about adding the `layout` and `stylesheet` class methods like `UIViewController` have is that doing so would create a question: where do you create your view hierarchy.  Now we're entering into Xcode world.  "Is _this_ the right place?" "If I put it here instead, is that wrong?".  I would rather have one preferred way (the `UIViewController##layout` method) and another feature that is flexible enough to cover all the other bases.

BUT, this is not just up to me!  If you still feel strongly about having this:
1. Open a pull request
2. Ask the community for support

If there is strong support for it, it will by all means be merged in.  I am only justifying why **I** will not write this feature.  I'm not saying it's dead in the water! :-)

**Comment by defvol** [comment]
Thanks, that worked pretty well. Looks like the only issue is with the frame property of the subviews (but that's just a couple of extra LOCs).

**Comment by colinta** [comment]
Lots of ways to set the frame:

frame: [[0,0], [100, 20]]
origin: [0,0]
size: [100,20]

Or set each one using top/left/width/height
