### ISSUE TITLE
Handlers being called 8x for every object placed

### ISSUE THREAD

**Issue by h6y3** [colinta/teacup#50]
I've noticed both in my own project and an isolated test that handlers are being called 8x in a stylesheet even if the call is made just once in the stylesheet and the object is added just once in the controller.

I created a gist with sample code to demonstrate the problem.

This is a problem because:
1.  Operations are being called unnecessarily and repeatedly (potential performance issue),
2.  Handlers were a way I had hoped I could use to call initialization and setup routines on my custom views (but this won't work if they are being called 8x).  For example, I created a custom carousel view that requires the image names to load.

Here's the gist: https://gist.github.com/3961878

**Comment by colinta** [comment]
wow, i thought I had that down to just once or twice!

the current design does result in having the style applied more than once, but this is a bit much. :-/

I have been kicking around an idea for a "2.0" version that will only apply styles once, when the view is loaded.  right now we have support for "orientation" styles, which is COOL, but adds to this overhead.  and those styles get applied when a rotation occurs, which can mess with views that have been animated or moved.

teacup 2.0 will focus on iOS 6, and we should encourage the use of autolayouts instead of orientation-styles.

i'll try and take a look at a short-term solution, but this might just have to wait...

**Comment by colinta** [comment]
OK, I think I had some success with this one!  Pull master - I haven't published it as a gem yet - and lemme know your mileage.

Thanks!

**Comment by h6y3** [comment]
Pulled the source, deleted the old gem, rebuilt the gem from source and this is what I got:

```
Build ./build/iPhoneSimulator-6.0-Development
Simulate ./build/iPhoneSimulator-6.0-Development/teacup-test.app
Objective-C stub for message `old_viewWillAppear:' type `v@:c' not precompiled. Make sure you properly link with the framework or library that defines this message.
(main)> *** simulator session ended with error: Error Domain=DTiPhoneSimulatorErrorDomain Code=1 "The simulated application quit." UserInfo=0x100414730 {NSLocalizedDescription=The simulated application quit., DTiPhoneSimulatorUnderlyingErrorCodeKey=-1}
rake aborted!
Command failed with status (1): [DYLD_FRAMEWORK_PATH="/Applications/Xcode.a...]
```

**Comment by colinta** [comment]
huh, interesting - I got that error when running the TESTS, but not when running my APP...

I'll start a fresh project and see if I can replicate it.

**Comment by colinta** [comment]
in the meantime, you could try removing these two lines:

116:    alias old_viewWillAppear viewWillAppear
...
119:      old_viewWillAppear(animated)

**Comment by h6y3** [comment]
I went ahead and published my harness for you.  https://github.com/h6y3/teacup-handler-test

**Comment by colinta** [comment]
Thanks, I do indeed get the error message.  Very odd indeed, because this WORKS in my project!  I've sent a bug report to Laurent, I'll see if I can get it nailed down in the meantime...

**Comment by h6y3** [comment]
I looked at it very briefly and couldn't crack the nut so it very well could be RubyMotion related if you didn't see the issue either.

**Comment by colinta** [comment]
Well this is fun: in the REPL, I can call those methods with no problem. :-|

**Comment by colinta** [comment]
Get THIS, if I don't assign the `rootViewController`, and do so after the app is loaded, I can add it to the `UIWindow`, and the `old_viewWillAppear(animated)` method gets called.  The plot thickens!

```
(main)> 2012-10-29 18:35:15.167 teacup-test[2163:11303] Application windows are expected to have a root view controller at the end of application launch

(I cmd+click on the window)

(#<UIWindow:0x93992a0>)> rootViewController = MyController.alloc.init
=> #<MyController:0x9454f00>
(#<UIWindow:0x93992a0>)> rootViewController.wantsFullScreenLayout = true
=> true
(#<UIWindow:0x93992a0>)> addSubview(rootViewController.view)
=============== ui_view_controller.rb at line 119, self = #<MyController:0x9454f00> ===============
DONE
Calling setup with arguments #<UITextField:0x9452fd0> and Hello world
=> #<UIWindow:0x93992a0>
```

Weeeird.

**Comment by colinta** [comment]
If I add the `old_viewWillAppear(animated)` method to `MyController`, I get a NEW error message!

```
Cannot define method `old_viewWillAppear:' because no Objective-C stub was pre-compiled for types `v@:c'. Make sure you properly link with the framework or library that defines this message.
```

Meanwhile, I `rake clean`'d the project where this DOES work, and it built fine and still runs.

**Comment by h6y3** [comment]
Did you try cleaning up the simulator assets too?  rake simulator clean=1.  Sometimes, I get weird artifacts between builds so I will `rake clean; rake simulator clean=1`

**Comment by colinta** [comment]
I'll give it a try!

**Comment by colinta** [comment]
No change, still all good.

**Comment by h6y3** [comment]
For the project that works, could it be related to your Gemspec somehow (do you have multiple copies of your old gem)?  For the harness I built, it doesn't use a Gemspec and I also removed your old Gem, rebuilt the gem, and then uninstalled the old gem and installed the built gem.  Its pretty unlikely this is the cause, but just a crazy guess on my part.

**Comment by colinta** [comment]
It's taken me this entire time to narrow it down: I'm including a project called "Kal", a (very good!) calendar view and controller.  Compiling the UIViewController subclass has something to do with it...

**Comment by colinta** [comment]
I was wrong - it wasn't the UIViewController subclass.  It's the presence of the Kal.bridgesupport file, and not just that, it's only a couple methods in there that "turn on" this method.  This is so strange.  It took me all NIGHT to narrow it down, but here it is:

###### Dummy.h

``` objc
#import <Foundation/Foundation.h>

enum {
  AnyType   = 0,
};
typedef char AnyOldType;

@interface Dummy : NSObject
- (void) setType:(AnyOldType)type;
- (AnyOldType) type;
@end
```

###### Dummy.m

``` objc
#import "Dummy.h"

@implementation Dummy
- (void) setType:(AnyOldType)type {}
- (AnyOldType) type {
    return AnyType;
}
@end
```

###### dummy.rb

``` ruby
class Dummy
  def anyMethodName
    @anyobject.type = nil
  end
end
```

See [pull request](https://github.com/h6y3/teacup-handler-test/pull/1) if you don't believe me.  It seriously took me 4-5 hours to narrow it down to these methods.

**Comment by h6y3** [comment]
Nice catch!  This makes sense - I'll check it out tonight.

**Comment by mfrawley** [comment]
Any update on when the performance fixes might make it into a stable Gem release? The latest Teacup is MUCH slower than previous versions, particularly if we're using more than one layout block per view controller.

**Comment by colinta** [comment]
Recent versions of teacup should have this all figured out - the `restyle!` method is called much less, and once per stylesheet change (e.g. changing the controller stylesheet will change the child view's stylesheets, but `restyle!` is only called at the end)
