### ISSUE TITLE
Handling UISwitch from Teacup Styles

### ISSUE THREAD

**Issue by GantMan** [colinta/teacup#60]
Trying to set UISwitch default to on.  layout code is:

``` ruby
@switch = subview(UISwitch, :custom_switch)
```

in viewDidLoad I can do this with

``` ruby
@switch.on = true
```

but removing that and trying to do it in Teacup with 

``` ruby
style :custom_switch,
  on: true
```

results in the following error:
**Objective-C stub for message `setOn:' type`v@:c' not precompiled. Make sure you properly link with the framework or library that defines this message.**

**Comment by colinta** [comment]
Fixed in 1.2.8.  I should have noticed the error message, that's an easy one to fix.  See the README about these "not precompiled" errors, and how to add them to `dummy.rb`, and you'll be able to fix these easily in the future.

Thanks, Gant!
