### ISSUE TITLE
Addition to the 10 second primer

### ISSUE THREAD

**Issue by chug2k** [colinta/teacup#67]
For all the n00bs like myself out there, it'd be awesome if you could mention adding the following line to your Rakefile:

```
app.files += Dir.glob(File.join(app.project_dir, 'styles/**/*.rb'))
```

**Comment by GantMan** [comment]
I completely agree.  I can remember when I had my "O YEAH" moment.

I currently have a pull request on the Readme.  Once it is closed I'll document this step.

**Comment by colinta** [comment]
I'm fine with adding this, but I wonder if instead we should change the README/examples to put the `styles` folder beneath the `app` folder.

**Comment by GantMan** [comment]
Good point.  I believe it should but this brings up a bigger question.

Shouldn't styles be able to be app specific and lib generic.

The use of styles have 2 benefits.  
- It separates the styling from the actual elements
- It is reusable ( _Including outside of each project_ )

The latter here would be ideal in RoR lib folder.  Whatever example is set in the README will be the current paradigm, but is it taking it too far to have a app/styles and a lib/styles ?  

Coming from RoR I'd prefer the above dual directory structure suggested.  Thoughts?

**Comment by chug2k** [comment]
I like moving it to app/styles, and I like documenting the simple, most common usage pattern in the README and examples.

I think if you're to the point where you're considering separating into lib/styles or vendor/styles, you're advanced enough to figure things out on your own. Besides, I would guess the majority of the time one styles folder will suffice.

**Comment by GantMan** [comment]
I agree guys, in the above Pull Request I did the following:

#### To the README

I added the comment, that styles should reside in `app/styles`

#### To the Hai Example

I moved the styles folder inside the `app` folder and removed the Rakefile include line.

#### To the Autolayout Example

I moved the app specific styles into the `app` folder, but kept the generic outside and in a `lib` folder.  Rakefile still pulls from this location.  As an example of mixing the two via import.
