### ISSUE TITLE
Sugarcube `uicolor` in titleColor handler

### ISSUE THREAD

**Issue by benastan** [colinta/teacup#68]
The error I'm getting:

```
handler.rb:52:in `block in apply:': undefined method `uicolor' for #<UICachedDeviceWhiteColor:0xbd4ab90> (NoMethodError)
```

[Code in z_handlers.rb](https://github.com/rubymotion/teacup/blob/master/lib/teacup/z_core_extensions/z_handlers.rb#L126)

Is sugarcube a dependency for teacup?

**Comment by GantMan** [comment]
I'm fairly sure it's not, otherwise it would be in the gemspec.  

Did a search, this is the only place this slipup happens.  Def would say it's a bug.

**Comment by colinta** [comment]
Ahh thanks, must have been a slip on my part!! :smiley:  Removing now...

**Comment by colinta** [comment]
removed in 1.3.2

**Comment by mfrawley** [comment]
Still seeing this on master, 1.3.3 release:

font = font.uifont, line 147 in z_handlers

**Comment by colinta** [comment]
Thanks for the heads up!  Removed in 1.3.4

**Comment by mfrawley** [comment]
Thanks for the quick response!
