### ISSUE TITLE
Using the new "auto" feature

### ISSUE THREAD

**Issue by stevebooks** [colinta/teacup#76]
When do you call the new "auto" method?

I am trying to call it in the viewDidLoad method, i.e.

def viewDidLoad
  super
  auto do
    horizontal "|-(>=1)-[logo(==262)]-(>=1)-|"
  end
end

Getting a bad memory access error.

Thanks

**Comment by colinta** [comment]
Hmm, that should be right. Do you have the motion-layout gem installed?

**Comment by stevebooks** [comment]
Yes, I have it installed

**Comment by stevebooks** [comment]
I made an example of what I was talking about:

https://github.com/stevebooks/teacup/tree/master/samples/AutoLayout

**Comment by GantMan** [comment]
I can verify that I get the same error.

I've tried playing around passing params and looking at the z_core_extension where the code is implemented.

Still errors.

**Comment by colinta** [comment]
Thanks for the demo app, I'm taking a look now.

**Comment by colinta** [comment]
It seems to be related to the `self.view` being present in the views dictionary.

**Comment by colinta** [comment]
Thanks again, guys!  Fixed in 5c14fef aka 2.0.0pre

**Comment by colinta** [comment]
![Screen Shot 2013-04-27 at 10 51 39 AM](https://f.cloud.github.com/assets/27570/434617/bfe0a238-af5a-11e2-92dd-3d467cb24927.png)

:smiley:
