### ISSUE TITLE
Autolayout Constraints Landscape

### ISSUE THREAD

**Issue by GantMan** [colinta/teacup#80]
I need to change my navigation bar image on landscape rotate.

As we've discussed in the past, this won't work with Autolayout as it currently stands.

Is there anything in the works for teacup 2.0 that will allow landscape blocks to be evaluated for autolayout?

Example: https://github.com/IconoclastLabs/MotionTemplate
looks like this when rotated... http://i.imgur.com/8ZvnlrR.png
I need to tell it to load another image on rotate.

**Comment by GantMan** [comment]
I'm going to solve my own problem with using `UIBarMetricsLandscapePhone` but I still think the issue might have merit, so I"m leaving it open.

**Comment by colinta** [comment]
I'm not sure auto layout helps here - the new UIAppearance system can help, though!
