### ISSUE TITLE
{frame: :full} not using parent frame size

### ISSUE THREAD

**Issue by vespakoen** [colinta/teacup#91]
I have the following view structure:

```
  0: . UIWindow(#10881e70, [[0.0, 0.0], [320.0, 480.0]])
  1: `-- UILayoutContainerView(#86b1770, [[0.0, 0.0], [320.0, 480.0]])
  2:     +-- UITransitionView(#86b2790, [[0.0, 0.0], [320.0, 431.0]])
  3:     |   `-- UIViewControllerWrapperView(#10881740, [[0.0, 20.0], [320.0, 411.0]])
  4:     |       `-- UIView(#a3085f0, [[0.0, 0.0], [320.0, 411.0]])
  5:     |           +-- UIImageView(#a3089c0, [[0.0, 0.0], [320.0, 460.0]]) stylename: :home_image
  6:     |           `-- UILabel(#a312160, [[0.0, 0.0], [320.0, 460.0]], text: "Ze title") stylename: :title_label
  7:     `-- UITabBar(#86b1830, [[0.0, 431.0], [320.0, 49.0]])
  ...
```

And the following stylesheet:

``` ruby
Teacup::Stylesheet.new :home_style do
  style :home_image,
    frame: :full

  style :title_label,
    frame: :full
end
```

As you can see, the UIView has the correct measurements, it fits exactly between the navigation and the tab bar. The childviews are however not the same size, but are bigger.

I tried using:

``` ruby
  layout do
    @home_image = subview(UIImageView, :home_image)
    @title_label = subview(UILabel, :title_label)
  end
```

and also:

``` ruby
def viewDidLoad
  layout(self.view) do
    @home_image = subview(UIImageView, :home_image)
    @title_label = subview(UILabel, :title_label)
  end
end
```

But to no avail.

Is there something I am doing incorrectly, or is this a bug?

**Comment by colinta** [comment]
Try adding an autoresingMask (flexible width & height), and see if that does the trick. 

The downside of `frame: :full` is when the parent view changes.

**Comment by vespakoen** [comment]
That works correct!
Now for another view, I want an image to be half the height of "the content" AKA screen height - navigationbar - tabbar.

I tried a couple of things:

``` ruby
  style :news_image,
    autoresizingMask: autoresize.fill,
    width: '100%',
    height: '50%'
```

``` ruby
  style :news_image,
    frame: :full,
    autoresizingMask: autoresize.fill,
    height: '50%'
```

``` ruby
  style :news_image,
    frame: :full,
    autoresizingMask: autoresize { flexible_width },
    height: '50%'
```

``` ruby
  style :news_image,
    frame: :full,
    autoresizingMask: autoresize { flexible_height },
    height: '50%'
```

In one case the image is to big, in another case it is too small.
Maybe I should use constraints / auto-layout to make this work?

**Comment by colinta** [comment]
Strange, the first one there (width 100%, height 50%) looks correct, with that autoresizingMask. What does the view hierarchy look like?

**Comment by vespakoen** [comment]
Thanks for the help so far!

Actually, I am probably doing quite some unusual stuff in my controllers, I am refactoring it at the moment to teacup, maybe when I finish the other views, I might walk into something that can cause this, if not, I will report back.

I'll close this for now
