### ISSUE TITLE
device undeclared before use in ui_view_controller.rb autorotateToOrientation

### ISSUE THREAD

**Issue by ninthspace** [colinta/teacup#92]
Whilst running an iOS 6 app under iOS 7, my application crashes when the keyboard is to be displayed. Examining the logs shows that this is due to an uncaught exception 'NameError'  reason: "undefined local variable or method `device'"

This is because in UIViewController.autorotateToOrientation, `device` isn't declared before its first use.

Adding `device = UIDevice.currentDevice.userInterfaceIdiom` beforehand resolves this issue.

**Comment by colinta** [comment]
hm, no, device in this case is a method on `Stylesheet`, which returns an integer mask of the device "attributes" (retina or not, ipad or not, iphone/iphone size).

Looking at it now.

**Comment by colinta** [comment]
I'm pushing v2.0.4 now, I didn't actually _change_ much, other than change `device` to `self.device`.  I'll be surprised if that fixes it, but worth a shot.

**Comment by ninthspace** [comment]
As you suspected `self.device` doesn't fix. Since I'm only targeting iOS 6 and later I took your advice in the comment above `autorotateToOrientation` to switch to `supportedInterfaceOrientation`, with `autorotateMask`. This works for me.

**Comment by colinta** [comment]
Oh, geez, I was looking in all the wrong places (I did a global search for `device` and somehow the `UIViewController` didn't show up, or more likely I didn't notice it).  I added the `device = ...` code like you mentioned, and pushed 2.0.5.  Thanks again!
